# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soundsride/service/soundsride_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+soundsride/service/soundsride_service.proto\"*\n\x14StartSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\x05\"\xca\x01\n\x1bUpdateTransitionSpecRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x15\n\rinitial_genre\x18\x02 \x01(\t\x12 \n\x0btransitions\x18\x03 \x03(\x0b\x32\x0b.Transition\x12\x18\n\x10\x63urrent_latitude\x18\x04 \x01(\x01\x12\x19\n\x11\x63urrent_longitude\x18\x05 \x01(\x01\x12\x18\n\x10\x63urrent_altitude\x18\x06 \x01(\x01\x12\x0f\n\x07next_up\x18\x07 \x01(\t\"\x93\x01\n\nTransition\x12\x14\n\x0ctransitionId\x18\x01 \x01(\t\x12\x1b\n\x13transition_to_genre\x18\x02 \x01(\t\x12$\n\x1c\x65stimated_time_to_transition\x18\x03 \x01(\x02\x12,\n$estimated_geo_distance_to_transition\x18\x04 \x01(\x02\"A\n\x12\x41udioChunkResponse\x12\x16\n\x0e\x66irst_frame_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x61udio_chunk\x18\x02 \x01(\x0c\"A\n\x08Position\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x02\"\x07\n\x05\x45mpty2\xe6\x01\n\nSoundsRide\x12\x18\n\x04Ping\x12\x06.Empty\x1a\x06.Empty\"\x00\x12/\n\x0cStartSession\x12\x06.Empty\x1a\x15.StartSessionResponse\"\x00\x12>\n\x14UpdateTransitionSpec\x12\x1c.UpdateTransitionSpecRequest\x1a\x06.Empty\"\x00\x12)\n\x08GetChunk\x12\x06.Empty\x1a\x13.AudioChunkResponse\"\x00\x12\"\n\x0bGetPosition\x12\x06.Empty\x1a\t.Position\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soundsride.service.soundsride_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STARTSESSIONRESPONSE']._serialized_start=47
  _globals['_STARTSESSIONRESPONSE']._serialized_end=89
  _globals['_UPDATETRANSITIONSPECREQUEST']._serialized_start=92
  _globals['_UPDATETRANSITIONSPECREQUEST']._serialized_end=294
  _globals['_TRANSITION']._serialized_start=297
  _globals['_TRANSITION']._serialized_end=444
  _globals['_AUDIOCHUNKRESPONSE']._serialized_start=446
  _globals['_AUDIOCHUNKRESPONSE']._serialized_end=511
  _globals['_POSITION']._serialized_start=513
  _globals['_POSITION']._serialized_end=578
  _globals['_EMPTY']._serialized_start=580
  _globals['_EMPTY']._serialized_end=587
  _globals['_SOUNDSRIDE']._serialized_start=590
  _globals['_SOUNDSRIDE']._serialized_end=820
# @@protoc_insertion_point(module_scope)
